Document: libnbcompat
Title: Debian libnbcompat Manual
Author: <insert document author here>
Abstract: This manual describes what libnbcompat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libnbcompat/libnbcompat.sgml.gz

Format: postscript
Files: /usr/share/doc/libnbcompat/libnbcompat.ps.gz

Format: text
Files: /usr/share/doc/libnbcompat/libnbcompat.text.gz

Format: HTML
Index: /usr/share/doc/libnbcompat/html/index.html
Files: /usr/share/doc/libnbcompat/html/*.html
